
import turtle
def toDraw_letter(color):
        letter = ["A","B","C","D","E","F","G","H"]
        t.pencolor(color)
        for i in letter:
                t.write(i,align="left",font=("microsoft yahei",20,"normal"))
                t.penup()
                t.forward(50)
                t.pendown()
        t.pencolor("black")
def toDraw_number(color):
        number = [1,2,3,4,5,6,7,8]
        t.pencolor(color)
        for i in number:
                t.write(i,align="left",font=("microsoft yahei",20,"normal"))
                t.penup()
                t.forward(50)
                t.pendown()
        t.pencolor("black")
def toDraw_lattice(color):
        t.fillcolor(color)
        t.begin_fill()
        for i in range(4):
                t.forward(50)
                t.left(90)
        t.end_fill()
        t.penup()
        t.forward(100)
def toDraw_pawn(color):
        t.pendown()
        t.fillcolor(color)
        t.begin_fill()
        t.forward(12)
        t.left(90)
        t.forward(5)
        t.left(80)
        for i in range(3):
            t.forward(4)
            t.right(30)
        t.left(10)
        t.forward(10)
        t.right(90)
        t.forward(3)
        t.left(90)
        t.forward(2)
        t.left(90)
        t.forward(6)
        t.right(180)
        t.circle(5)
        t.left(180)
        t.forward(6)
        t.left(90)
        t.forward(2)
        t.left(90)
        t.forward(3)
        t.right(90)
        t.forward(9)
        t.right(10)
        for i in range(3):
            t.forward(4)
            t.right(30)
        t.right(80)
        t.left(180)
        t.forward(5)
        t.left(90)
        t.forward(11)
        t.end_fill()
        t.penup()
def toDraw_knight(color):
        t.pendown()
        t.fillcolor(color)
        t.begin_fill()
        t.forward(20)
        t.left(90)
        for i in range(12):
            t.forward(2)
            t.left(1)
        t.forward(20)
        t.left(60)
        t.forward(5)
        t.left(45)
        t.forward(25)
        t.left(30)
        for i in range(3):
                t.forward(4)
                t.left(30)
        t.left(30)
        t.forward(10)
        t.right(100)
        t.forward(5)
        for i in range(4):
            t.forward(1)
            t.right(1)
        for i in range(5):
            t.forward(2)
            t.left(1)
        t.forward(4)
        t.left(101)
        t.forward(9)
        t.end_fill()
        t.penup()
def toDraw_rook(color):
        pass
def toDraw_bishop(color):
        t.pendown()
        t.fillcolor(color)
        t.begin_fill()
        t.forward(12)
        t.left(90)
        t.forward(5)
        t.left(80)
        for i in range(3):
            t.forward(4)
            t.right(32)
        t.left(10)
        t.forward(15)
        t.left(100)
        t.forward(5)
        t.left(180)
        t.circle(8)
        t.penup()
        t.goto(0,0)
        t.pendown()
        t.left(175)
        t.forward(12)
        t.right(90)
        t.forward(5)
        t.right(80)
        for i in range(3):
            t.forward(4)
            t.left(32)
        t.right(10)
        t.forward(15)
        t.right(100)
        t.forward(6)
        t.end_fill()
        t.penup()
        t.left(183)
        t.forward(1)
        t.right(90)
        t.forward(1)
        if color=="white":
                t.pencolor(c)
        else:
                t.pencolor("black")
        t.pendown()
        t.pensize(3)
        for i in range(4):
            t.forward(5)
            t.right(90)
            t.forward(5)
            t.left(180)
        t.penup()
        t.forward(19)
        t.left(90)
        t.pendown()
        t.pencolor(color)
        t.circle(2)
        t.penup()
def toDraw_queen(color):
        pass
def toDraw_king(color):
        pass

#main
t = turtle.Turtle()
t.speed(0)
t.penup()
t.left(180)
#Start print outline
t.pensize(5)
t.goto(-240,240)
t.fillcolor("moccasin")
t.begin_fill()
t.pendown()
for i in range(4):
	t.left(90)
	t.forward(480)
t.penup()
t.end_fill()
t.pensize(1)
#Start print outline
t.pensize(3)
t.goto(-200,200)
t.pendown()
t.fillcolor("moccasin")
t.begin_fill()
for i in range(4):
	t.left(90)
	t.forward(400)
t.end_fill()
t.pensize(1)
#Start print letters
t.left(180)
t.penup()
t.goto(-183,200)
t.pendown()
toDraw_letter("midnightblue")
t.penup()
t.goto(-223,157)
t.right(90)
toDraw_number("midnightblue")
t.penup()
t.goto(167,-237)
t.right(90)
letter = ["A","B","C","D","E","F","G","H"]
letter.reverse
for i in letter:
        t.pencolor("midnightblue")
        t.write(i,align="left",font=("microsoft yahei",20,"normal"))
        t.penup()
        t.forward(50)
        t.pendown()
        t.pencolor("black")
t.penup()
t.goto(210,157)
t.left(90)
toDraw_number("midnightblue")
#Start print lattice
t.penup()
t.goto(-200,200)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(-150,150)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(-100,200)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(-50,150)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(0,200)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(50,150)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(100,200)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(150,150)
for i in range(4):
        t.pendown()
        toDraw_lattice("midnightblue")
        t.penup()
t.goto(-176,108)
t.left(90)
for i in range(8):
        toDraw_pawn("black")
        t.forward(48.555)
t.goto(-200,200)
